[build]
  publish = "public"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "max-age=31536001"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"


[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache"