name: build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  contents: read
jobs:
  build-and-test:
    name: "${{ matrix.platform }}: node.js ${{ matrix.node-version }}"
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
        node-version: [24]
        include:
          - platform: ubuntu-latest
            node-version: 24
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> "$GITHUB_OUTPUT"
      - name: Cache Yarn
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
      - name: Install
        run: yarn install
      - name: Validate component gallery build
        run: yarn build-gallery
      - name: Rebuild Elements README
        run: cd elements && for dir in */; do head -4 $dir/README.md; done > README.md
